### ISSUE TITLE
Status UP even if deployment failed

### ISSUE THREAD

**Issue by rsoika** [eclipse/microprofile-health#288]
I have a general conceptual question about microprofile-health api.

In my application I implemented a details health status which results in a output with HTTP Code 200 as followed:

```json
{
	"status": "UP",
	"checks": [
		{
			"name": "imixs-workflow",
			"status": "UP",
			"data": {
				"engine.version": "5.2.9-SNAPSHOT",
				"model.groups": 1,
				"model.versions": 1,
				"index.status": "ok",
				"database.status": "ok"
			}
		},
		{
			"name": "ready-deployment.imixs-office-workflow.war",
			"status": "UP"
		}
	]
}
```

I am running this on Wildfly. 
My Kubernetes health check looks like this:

```yaml
spec:
  containers:
    ...
    livenessProbe:
      httpGet:
        path: /health
        port: 9990
      initialDelaySeconds: 120
      periodSeconds: 10
      failureThreshold: 3
   ...
```

So I am using the default behaviour from Kubernetes here to validate the http response code 200=OK.

But I run into situations where something bad happens and my application did not start correctly and is not deployed at all. This results on the server in a health status like this:

```json
{
	"status": "UP",
}
```

And so again we have http response code 200=OK.

Is there any chance in eclipse microprofile-health to force the Status=DOWN in case a specific deployment is missing?
